[package]
name = "libtimeleft"
version = "0.1.3"
edition = "2021"
description = "Library used for timeleft"
license = "Apache-2.0"

[dependencies.chrono]
version = "0.4.22"
features = ["serde"]

[dependencies.serde]
version = "1.0.147"
features = ["derive"]
